lst_carac:
  - carac_name: "NB AUBES"
    row_type: "ROTOR"
    Nb_hauteur_base: 1
  - carac_name: "NB AUBES"
    row_type: "STATOR"
    Nb_hauteur_base: 1
#  - carac_name: "RBA"
#    row_type: "ROTOR"
#  - carac_name: "RBA"
#    row_type: "STATOR"
#  - carac_name: "RBF"
#    row_type: "ROTOR"
#  - carac_name: "RBF"
#    row_type: "STATOR"
#  - carac_name: "RBA GENEPI"
#    row_type: "ROTOR"
#  - carac_name: "RBA GENEPI"
#    row_type: "STATOR"
#  - carac_name: "RBF GENEPI"
#    row_type: "ROTOR"
#  - carac_name: "RBF GENEPI"
    row_type: "STATOR"
  - carac_name: "SSC"
    row_type: "ROTOR"
  - carac_name: "SSC"
    row_type: "STATOR"
  - carac_name: "SSC GENEPI"
    row_type: "ROTOR"
  - carac_name: "SSC GENEPI"
    row_type: "STATOR"
  - carac_name: "CALAGE"
    row_type: "ROTOR"
  - carac_name: "CALAGE"
    row_type: "STATOR"
  - carac_name: "CALAGE GENEPI"
    row_type: "ROTOR"
  - carac_name: "CALAGE GENEPI"
    row_type: "STATOR"
  - carac_name: "CORDE"
    row_type: "ROTOR"
  - carac_name: "CORDE"
    row_type: "STATOR"
  - carac_name: "CORDE GENEPI"
    row_type: "ROTOR"
  - carac_name: "CORDE GENEPI"
    row_type: "STATOR"
  - carac_name: "CORDE AXIAL"
    row_type: "ROTOR"
  - carac_name: "CORDE AXIAL"
    row_type: "STATOR"
  - carac_name: "EMAX"
    row_type: "ROTOR"
  - carac_name: "EMAX"
    row_type: "STATOR"
  - carac_name: "EMAX GENEPI"
    row_type: "ROTOR"
  - carac_name: "EMAX GENEPI"
    row_type: "STATOR"
  - carac_name: "EMAXSC"
    row_type: "ROTOR"
  - carac_name: "EMAXSC"
    row_type: "STATOR"
  - carac_name: "EMAXSC GENEPI"
    row_type: "ROTOR"
  - carac_name: "EMAXSC GENEPI"
    row_type: "STATOR"
  - carac_name: "XEMAXSC"
    row_type: "ROTOR"
  - carac_name: "XEMAXSC"
    row_type: "STATOR"
  - carac_name: "XEMAXSC GENEPI"
    row_type: "ROTOR"
  - carac_name: "XEMAXSC GENEPI"
    row_type: "STATOR"
  - carac_name: "HSC"
    row_type: "ROTOR"
  - carac_name: "HSC"
    row_type: "STATOR"
  - carac_name: "HSC GENEPI"
    row_type: "ROTOR"
  - carac_name: "HSC GENEPI"
    row_type: "STATOR"
  - carac_name: "DLI"
    row_type: "STATOR"
  - carac_name: "DLI"
    row_type: "ROTOR"
  - carac_name: "DLI GENEPI"
    row_type: "STATOR"
  - carac_name: "DLI GENEPI"
    row_type: "ROTOR"
  - carac_name: "DHSU2"
    row_type: "ROTOR"
  - carac_name: "PSIA"
    row_type: "ROTOR"
  - carac_name: "PSIA"
    row_type: "STATOR"
  - carac_name: "PSIA GENEPI"
    row_type: "ROTOR"
  - carac_name: "PSIA GENEPI"
    row_type: "STATOR"
  - carac_name: "VZSU"
    row_type: "ROTOR"
  - carac_name: "DSS GENEPI"
    row_type: "ROTOR"
    Nb_hauteur_base: 1
  - carac_name: "DSS"
    row_type: "ROTOR"
    Nb_hauteur_base: 1
  - carac_name: "DSTD1"
    row_type: "ROTOR"
    Nb_hauteur_base: 1
  - carac_name: "KD"
    row_type: "PLANS"
    Nb_hauteur_base: 1
  - carac_name: "JEU AXIAL"
    row_type: "ALL"
